#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libshout
Version  : 2.4.3
Release  : 1
URL      : http://downloads.xiph.org/releases/libshout/libshout-2.4.3.tar.gz
Source0  : http://downloads.xiph.org/releases/libshout/libshout-2.4.3.tar.gz
Summary  : Audio streaming library for icecast encoders
Group    : Development/Tools
License  : LGPL-2.0
Requires: libshout-lib = %{version}-%{release}
Requires: libshout-license = %{version}-%{release}
BuildRequires : pkgconfig(speex)
BuildRequires : pkgconfig(theora)
BuildRequires : pkgconfig(vorbis)

%description
libshout
--------
Libshout is a library for communicating with and sending data to an
icecast server.  It handles the socket connection, the timing of the
data, and prevents bad data from getting to the icecast server.

%package dev
Summary: dev components for the libshout package.
Group: Development
Requires: libshout-lib = %{version}-%{release}
Provides: libshout-devel = %{version}-%{release}
Requires: libshout = %{version}-%{release}

%description dev
dev components for the libshout package.


%package doc
Summary: doc components for the libshout package.
Group: Documentation

%description doc
doc components for the libshout package.


%package lib
Summary: lib components for the libshout package.
Group: Libraries
Requires: libshout-license = %{version}-%{release}

%description lib
lib components for the libshout package.


%package license
Summary: license components for the libshout package.
Group: Default

%description license
license components for the libshout package.


%prep
%setup -q -n libshout-2.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560793349
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1560793349
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libshout
cp COPYING %{buildroot}/usr/share/package-licenses/libshout/COPYING
cp src/common/avl/COPYING %{buildroot}/usr/share/package-licenses/libshout/src_common_avl_COPYING
cp src/common/httpp/COPYING %{buildroot}/usr/share/package-licenses/libshout/src_common_httpp_COPYING
cp src/common/net/COPYING %{buildroot}/usr/share/package-licenses/libshout/src_common_net_COPYING
cp src/common/thread/COPYING %{buildroot}/usr/share/package-licenses/libshout/src_common_thread_COPYING
cp src/common/timing/COPYING %{buildroot}/usr/share/package-licenses/libshout/src_common_timing_COPYING
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/ckport/db/libshout.ckport

%files dev
%defattr(-,root,root,-)
/usr/include/shout/shout.h
/usr/lib64/libshout.so
/usr/lib64/pkgconfig/shout.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libshout/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libshout.so.3
/usr/lib64/libshout.so.3.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libshout/COPYING
/usr/share/package-licenses/libshout/src_common_avl_COPYING
/usr/share/package-licenses/libshout/src_common_httpp_COPYING
/usr/share/package-licenses/libshout/src_common_net_COPYING
/usr/share/package-licenses/libshout/src_common_thread_COPYING
/usr/share/package-licenses/libshout/src_common_timing_COPYING
